{
 "title": "OpenWeather",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Skyer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(openweather_clouds[30m])) / sum(count_over_time(openweather_clouds[30m]))",
     "legendFormat": "openweather_clouds"
    }
   ]
  },
  {
   "title": "Vindhastighed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(openweather_windspeed[30m])) / sum(count_over_time(openweather_windspeed[30m]))",
     "legendFormat": "openweather_windspeed"
    }
   ]
  },
  {
   "title": "Sea Level Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(openweather_qnh[30m])) / sum(count_over_time(openweather_qnh[30m]))",
     "legendFormat": "openweather_qnh"
    }
   ]
  },
  {
   "title": "Udendørs luftfugtighed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(openweather_humidity[30m])) / sum(count_over_time(openweather_humidity[30m]))",
     "legendFormat": "openweather_humidity"
    }
   ]
  }
 ]
}