{
 "title": "Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 14, "x": 5, "y": 0 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bme_temperature{instance=~\".*\"})",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum(bme_temperature{instance=~\".*\"})",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Højde",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(bme_altitude{instance=~\".*\"}[7d])) / sum(count_over_time(bme_altitude{instance=~\".*\"}[7d]))",
     "legendFormat": "altitude_7d"
    },
    {
     "expr": "sum(bme_altitude{instance=~\".*\"})",
     "legendFormat": "altitude_current_est"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "sum(bme_humidity{instance=~\".*\"})",
     "legendFormat": "humidity"
    }
   ]
  },
  {
   "title": "RGB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcs_blue{instance=~\".*\"})",
     "legendFormat": "blue"
    },
    {
     "expr": "sum(tcs_green{instance=~\".*\"})",
     "legendFormat": "green"
    },
    {
     "expr": "sum(tcs_red{instance=~\".*\"})",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "Elforbrug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "quantity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Sound level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mems_sound_avg{instance=~\".*\"})",
     "legendFormat": "mems_sound_avg"
    },
    {
     "expr": "sum(mems_sound_loud{instance=~\".*\"})",
     "legendFormat": "mems_sound_loud"
    }
   ]
  }
 ]
}